// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WellbeingTracking.Infrastructure.Data;

#nullable disable

namespace WellbeingTracking.Infrastructure.Migrations
{
    [DbContext(typeof(WellbeingDbContext))]
    [Migration("20260311073253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WellbeingTracking.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecId"));

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recommendation");

                    b.Property<string>("StressRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stress_range");

                    b.HasKey("RecId");

                    b.ToTable("Recommendations");

                    b.HasData(
                        new
                        {
                            RecId = 1,
                            RecommendationText = "Suggest productivity or mindfulness tips",
                            StressRange = "0-3"
                        },
                        new
                        {
                            RecId = 2,
                            RecommendationText = "Suggest physical activity or short breaks",
                            StressRange = "4-7"
                        },
                        new
                        {
                            RecId = 3,
                            RecommendationText = "Suggest breathing or relaxation exercises",
                            StressRange = "8-10"
                        });
                });

            modelBuilder.Entity("WellbeingTracking.Domain.Entities.WellbeingLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mood");

                    b.Property<double>("SleepHours")
                        .HasColumnType("float")
                        .HasColumnName("sleep_hours");

                    b.Property<int>("StressLevel")
                        .HasColumnType("int")
                        .HasColumnName("stress_level");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.ToTable("WellbeingLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
